export const AUTHENTICATION = 'AUTHENTICATION';
export const LOGOUT = 'LOGOUT';

export const AJAX_POSTS_LIST = 'AJAX_POSTS_LIST';
export const AJAX_POST_DETAILS = 'AJAX_POST_DETAILS';

export const PAGE_CHANGE = 'PAGE_CHANGE';

// VISIBILITY ACTIONS
export const CHANGE_LOGIN_VISIBILITY = 'CHANGE_LOGIN_VISIBILITY';
